# Generated by Django 5.2.9 on 2025-12-24 06:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_alter_item_item_name_alter_vendor_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount in rupees', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Amount (₹)')),
                ('sales_commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed sales commission amount in rupees', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sales Commission Amount (₹)')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_pricings', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_pricings', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='companies.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Pricing',
                'verbose_name_plural': 'Customer Pricings',
                'db_table': 'customer_pricing',
                'ordering': ['-created_at', 'customer'],
                'indexes': [models.Index(fields=['company', 'customer'], name='customer_pr_company_c24499_idx'), models.Index(fields=['valid_from', 'valid_to'], name='customer_pr_valid_f_50a0ab_idx'), models.Index(fields=['is_active'], name='customer_pr_is_acti_064e75_idx'), models.Index(fields=['created_at'], name='customer_pr_created_87e2cc_idx')],
                'unique_together': {('company', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='ItemPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Year')),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Month')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Purchase Price (₹)')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Retail Price (MRP) (₹)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pricings', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_pricings', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='companies.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item Pricing',
                'verbose_name_plural': 'Item Pricings',
                'db_table': 'item_pricing',
                'ordering': ['-year', '-month', 'item'],
                'indexes': [models.Index(fields=['company', 'item'], name='item_pricin_company_7cc7c6_idx'), models.Index(fields=['year', 'month'], name='item_pricin_year_2b36cf_idx'), models.Index(fields=['is_active'], name='item_pricin_is_acti_4ea6f9_idx'), models.Index(fields=['created_at'], name='item_pricin_created_3e49e9_idx')],
                'unique_together': {('company', 'item', 'year', 'month')},
            },
        ),
    ]
