# Generated by Django 5.2.7 on 2026-01-08 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_customerpricing_itempricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order Number')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('load_type', models.CharField(choices=[('refill', 'Refill'), ('emr', 'EMR'), ('empty', 'Empty'), ('pipeline', 'Pipeline'), ('others', 'Others')], default='refill', max_length=20, verbose_name='Load Type')),
                ('cylinder_place', models.TextField(verbose_name='Cylinder Place/Address')),
                ('transport_required', models.BooleanField(default=False, verbose_name='Transport Required')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Quantity')),
                ('total_empty_cylinders', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Empty Cylinders')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to='companies.createemployee', verbose_name='Employee')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='companies.vendor', verbose_name='Vendor')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to='companies.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Vendor Order',
                'verbose_name_plural': 'Vendor Orders',
                'db_table': 'vendor_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, verbose_name='Item Code')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('empty_cylinders', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Empty Cylinders')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('is_transport', models.BooleanField(default=False, verbose_name='Transport Included')),
                ('transport_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Transport Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_order_items', to='companies.item', verbose_name='Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='companies.vendororder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Vendor Order Item',
                'verbose_name_plural': 'Vendor Order Items',
                'db_table': 'vendor_order_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendororder',
            index=models.Index(fields=['company', 'vendor'], name='vendor_orde_company_6ed4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='vendororder',
            index=models.Index(fields=['order_number'], name='vendor_orde_order_n_689b19_idx'),
        ),
        migrations.AddIndex(
            model_name='vendororder',
            index=models.Index(fields=['invoice_number'], name='vendor_orde_invoice_cc77fb_idx'),
        ),
        migrations.AddIndex(
            model_name='vendororder',
            index=models.Index(fields=['status'], name='vendor_orde_status_b0d018_idx'),
        ),
        migrations.AddIndex(
            model_name='vendororder',
            index=models.Index(fields=['created_at'], name='vendor_orde_created_827539_idx'),
        ),
    ]
