# Generated by Django 5.2.7 on 2026-01-13 10:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_vendororder_vendororderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Physical Stock')),
                ('empty_with_customers', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Empty Cylinders with Customers')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stocks', to='companies.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD_STOCK', 'Add Physical Stock'), ('REMOVE_STOCK', 'Remove Physical Stock'), ('CUSTOMER_RETURN', 'Customer Returns Empty'), ('CUSTOMER_TAKE', 'Customer Takes Cylinders'), ('MANUAL_ADJUSTMENT', 'Manual Stock Adjustment'), ('VENDOR_ORDER', 'Vendor Order'), ('CUSTOMER_ORDER', 'Customer Order')], max_length=50, verbose_name='Transaction Type')),
                ('previous_physical_stock', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Previous Physical Stock')),
                ('previous_empty_customers', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Previous Empty with Customers')),
                ('new_physical_stock', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='New Physical Stock')),
                ('new_empty_customers', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='New Empty with Customers')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stock_transactions', to='companies.item', verbose_name='Item')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='companies.stock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'db_table': 'stock_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['company', 'item'], name='stocks_company_11b51f_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['physical_stock'], name='stocks_physica_d3ece3_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_updated'], name='stocks_last_up_0781d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('company', 'item')},
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['company', 'item'], name='stock_trans_company_f01cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='stock_trans_transac_b2b788_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['created_at'], name='stock_trans_created_1ba426_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['reference_number'], name='stock_trans_referen_657dd0_idx'),
        ),
    ]
