# Generated by Django 5.2.9 on 2026-01-18 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_stock_stocktransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororderitem',
            name='empty_cylinders',
            field=models.IntegerField(default=0, verbose_name='Empty Cylinders'),
        ),
        migrations.AlterField(
            model_name='vendororderitem',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
    ]
