# Generated by Django 5.2.7 on 2026-01-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_alter_vendororderitem_empty_cylinders_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendororder',
            unique_together={('company', 'invoice_number')},
        ),
    ]
